### ISSUE TITLE
SyntaxError: ipython.set_next_input(..)

### ISSUE THREAD

**Issue by EricJLarson** [massgh/ipyslides#1]
I have installed ipslides 0.8.7 and ipy 7.27.0.

When I run `import ipyslides` I get the following error:
```
File "/usr/local/lib/python3.7/dist-packages/ipyslides/__init__.py", line 36
  ipython.set_next_input(f'{code_after}\n{initial_code}', replace= True)

SyntaxError: invalid syntax
```

**Comment by massgh** [comment]
Which IDE you are using? Jupyterlab 3 is optimized at best. Some editors like Google colab do not support writing code by ipython. So you can write code yourself instead of using `initialize()`
You can do this too

```python
import ipyslides as isd
from ipyslides.utils import write, plt2html, print_context, fmt2cols
from ipyslides.core import  LiveSlides
ls = LiveSlides() # This registers %%slide and %%title magics as bonus

# Note: For LiveSlides('A'), use %%slideA, %%titleA, LiveSlides('B'), use %%slideB, %%titleB
# so that they do not overwite each other's slides.

ls.convert2slides(True) #Set this to True for Slides output
ls.set_footer('Author: Abdul Saboor')
ls.align8center(True) # Set False to align top-left corner

with ls.title():
    write('# Title Page')
with ls.slide(1):
    write('## Bemo Slides')
    display(slides)
    
for i in range(2,5):
    with ls.slide(i):
        write(f'## Slide {i} Title')

ls.show()
```
See example slides at [Kaggle](https://www.kaggle.com/massgh/ipyslides)

**Comment by asaboor-gh** [comment]
> I have installed ipslides 0.8.7 and ipy 7.27.0.
> 
> When I run `import ipyslides` I get the following error:
> 
> ```
> File "/usr/local/lib/python3.7/dist-packages/ipyslides/__init__.py", line 36
>   ipython.set_next_input(f'{code_after}\n{initial_code}', replace= True)
> 
> SyntaxError: invalid syntax
> ```

I did this with ipy 7 in colab and ipy 7.4 in my local machine. Is it some unstable version of ipython that throws error? Let me check with the version you are using

**Comment by asaboor-gh** [comment]
I just checked with versions you used. It's working even in ipython terminal (where you can not even display slides)
```python
❯(test_ipy)  ipython
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ipyslides as isd

In [2]: isd.__version__
Out[2]: '0.8.7'

In [3]: isd.initialize()
Copy lines below in a cell and execute
 import ipyslides as isd
...  # Same lines as in previous comment
```

So it may be editor issue. Or you can also try deleting \_\_pycache\_\_ folders to troubleshoot

**Comment by EricJLarson** [comment]
This was a user error.  I was attempting to run this in Python, not IPython.  
It works in IPython.
