### ISSUE TITLE
No package code in sdist

### ISSUE THREAD

**Issue by thewchan** [massgh/ipyslides#3]
Hi, there must be something that have gone awry as none of the package code are in the PyPI sdist:
![image](https://user-images.githubusercontent.com/49702524/210148868-4738ef17-65f3-41f8-9a5d-88e538804a36.png)

Can we address this?

**Comment by asaboor-gh** [comment]
Which version of `ipyslides` you are using? 
It will help me to check things on my side easily.

**Comment by thewchan** [comment]
This is from the most recent version available on PyPI, 3.0.2: https://files.pythonhosted.org/packages/b8/37/61974068c2b2ed3b3b92a26615d296b09a0850fed32b92f87820a9b12f42/ipyslides-3.0.2.tar.gz

**Comment by asaboor-gh** [comment]
You are right, it somehow is not picking up code in tar.gz, see size of two files in screenshot below.
This needs to overwrite all releases with empty code and republish on PyPi. You will be able to get version 3.0.0 corrected today. I will leave a comment after resetting. This will still be ahead of 3.0.2, so no worries about losing things.
![image](https://user-images.githubusercontent.com/48522862/210150426-ac0a06af-7027-4a07-beb9-7f18ae8e73bc.png)

**Comment by asaboor-gh** [comment]
I just update version 3.0.3rc1, because unfortunately, we can no longer overwrite a PyPi package.

**Comment by asaboor-gh** [comment]
Thanks for pointing it out. Since I am using development install, I pushed many versions without noticing it.

**Comment by asaboor-gh** [comment]
> This is from the most recent version available on PyPI, 3.0.2: https://files.pythonhosted.org/packages/b8/37/61974068c2b2ed3b3b92a26615d296b09a0850fed32b92f87820a9b12f42/ipyslides-3.0.2.tar.gz

You can now safely use most recent and feature complete version 3.0.4.
